# Form implementation generated from reading ui file 'analysis_logged_in.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Analysis(object):
    def setupUi(self, Analysis):
        Analysis.setObjectName("Analysis")
        Analysis.resize(1021, 777)
        self.centralwidget = QtWidgets.QWidget(parent=Analysis)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.backgroundFrame.setGeometry(QtCore.QRect(-10, 0, 1031, 731))
        self.backgroundFrame.setStyleSheet("background-color:#F4F3F3;\n"
"border:none")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.headerFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 1031, 121))
        self.headerFrame.setStyleSheet("background-color: #CECECE;\n"
"")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.headerFooter = QtWidgets.QFrame(parent=self.headerFrame)
        self.headerFooter.setGeometry(QtCore.QRect(10, 104, 1021, 21))
        self.headerFooter.setStyleSheet("background-color:#BCBCBC;\n"
"border:none\n"
"")
        self.headerFooter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFooter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFooter.setObjectName("headerFooter")
        self.btnProfileSettings = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnProfileSettings.setGeometry(QtCore.QRect(900, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(-1)
        self.btnProfileSettings.setFont(font)
        self.btnProfileSettings.setStyleSheet("color: black;\n"
"background-color: #BCBCBC;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n"
"border:none\n"
"")
        self.btnProfileSettings.setObjectName("btnProfileSettings")
        self.btnDashboard = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnDashboard.setGeometry(QtCore.QRect(760, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(-1)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setStyleSheet("color: black;\n"
"background-color: #BCBCBC;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n"
"border:none\n"
"\n"
"   ")
        self.btnDashboard.setObjectName("btnDashboard")
        self.btnHome = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnHome.setGeometry(QtCore.QRect(620, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(-1)
        self.btnHome.setFont(font)
        self.btnHome.setStyleSheet("color: black;\n"
"background-color: #BCBCBC;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n"
"border:none\n"
"   ")
        self.btnHome.setObjectName("btnHome")
        self.lblDashboardHeader = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblDashboardHeader.setGeometry(QtCore.QRect(10, 70, 161, 31))
        self.lblDashboardHeader.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 20px;\n"
"background-color: #CECECE;\n"
"color: black;\n"
"   ")
        self.lblDashboardHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblDashboardHeader.setObjectName("lblDashboardHeader")
        self.lblTitle = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblTitle.setGeometry(QtCore.QRect(60, 10, 181, 31))
        self.lblTitle.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 20px;\n"
"background-color: #CECECE;\n"
"color: black;\n"
"   ")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.lblLogo = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblLogo.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.lblLogo.setObjectName("lblLogo")
        self.lineBetweenHomeAndDashboard = QtWidgets.QFrame(parent=self.headerFrame)
        self.lineBetweenHomeAndDashboard.setGeometry(QtCore.QRect(746, 13, 1, 45))
        self.lineBetweenHomeAndDashboard.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenHomeAndDashboard.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenHomeAndDashboard.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenHomeAndDashboard.setObjectName("lineBetweenHomeAndDashboard")
        self.lineBetweenDashboardAndProfileSettings = QtWidgets.QFrame(parent=self.headerFrame)
        self.lineBetweenDashboardAndProfileSettings.setGeometry(QtCore.QRect(885, 13, 1, 45))
        self.lineBetweenDashboardAndProfileSettings.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenDashboardAndProfileSettings.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenDashboardAndProfileSettings.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenDashboardAndProfileSettings.setObjectName("lineBetweenDashboardAndProfileSettings")
        self.footerFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.footerFrame.setGeometry(QtCore.QRect(10, 660, 1021, 61))
        self.footerFrame.setStyleSheet("background-color:#CECECE;\n"
"border:none")
        self.footerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footerFrame.setObjectName("footerFrame")
        self.btnSupport = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnSupport.setGeometry(QtCore.QRect(900, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(-1)
        self.btnSupport.setFont(font)
        self.btnSupport.setStyleSheet("color: black;\n"
"background-color: #BCBCBC;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n"
"border:none;\n"
"   ")
        self.btnSupport.setObjectName("btnSupport")
        self.btnAbout = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnAbout.setGeometry(QtCore.QRect(760, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(-1)
        self.btnAbout.setFont(font)
        self.btnAbout.setStyleSheet("color: black;\n"
"background-color: #BCBCBC;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n"
"   ")
        self.btnAbout.setObjectName("btnAbout")
        self.btnLinkedIn = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnLinkedIn.setGeometry(QtCore.QRect(0, 30, 41, 21))
        self.btnLinkedIn.setObjectName("btnLinkedIn")
        self.btnGitHub = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnGitHub.setGeometry(QtCore.QRect(40, 30, 41, 21))
        self.btnGitHub.setObjectName("btnGitHub")
        self.lineBetweenAboutAndSupport = QtWidgets.QFrame(parent=self.footerFrame)
        self.lineBetweenAboutAndSupport.setGeometry(QtCore.QRect(885, 5, 1, 45))
        self.lineBetweenAboutAndSupport.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenAboutAndSupport.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenAboutAndSupport.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenAboutAndSupport.setObjectName("lineBetweenAboutAndSupport")
        self.lineBetweenFAQsAndAbout = QtWidgets.QFrame(parent=self.footerFrame)
        self.lineBetweenFAQsAndAbout.setGeometry(QtCore.QRect(746, 5, 1, 45))
        self.lineBetweenFAQsAndAbout.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenFAQsAndAbout.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenFAQsAndAbout.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenFAQsAndAbout.setObjectName("lineBetweenFAQsAndAbout")
        self.btnFAQs = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnFAQs.setGeometry(QtCore.QRect(620, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(-1)
        self.btnFAQs.setFont(font)
        self.btnFAQs.setStyleSheet("color: black;\n"
"background-color: #BCBCBC;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n"
"   ")
        self.btnFAQs.setObjectName("btnFAQs")
        self.loginFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.loginFrame.setGeometry(QtCore.QRect(240, 220, 571, 391))
        self.loginFrame.setStyleSheet("background-color: #CECECE;\n"
"")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.txtEma10 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtEma10.setGeometry(QtCore.QRect(90, 30, 131, 21))
        self.txtEma10.setToolTipDuration(0)
        self.txtEma10.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtEma10.setText("")
        self.txtEma10.setReadOnly(True)
        self.txtEma10.setObjectName("txtEma10")
        self.txtEma50 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtEma50.setGeometry(QtCore.QRect(90, 90, 131, 21))
        self.txtEma50.setToolTipDuration(0)
        self.txtEma50.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtEma50.setReadOnly(True)
        self.txtEma50.setObjectName("txtEma50")
        self.lblEma10 = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblEma10.setGeometry(QtCore.QRect(20, 30, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblEma10.setFont(font)
        self.lblEma10.setToolTipDuration(0)
        self.lblEma10.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblEma10.setObjectName("lblEma10")
        self.lblEma50 = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblEma50.setGeometry(QtCore.QRect(20, 90, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblEma50.setFont(font)
        self.lblEma50.setToolTipDuration(0)
        self.lblEma50.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblEma50.setIndent(0)
        self.lblEma50.setObjectName("lblEma50")
        self.txtEma34 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtEma34.setGeometry(QtCore.QRect(90, 60, 131, 21))
        self.txtEma34.setToolTipDuration(0)
        self.txtEma34.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtEma34.setReadOnly(True)
        self.txtEma34.setObjectName("txtEma34")
        self.lblEma34 = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblEma34.setGeometry(QtCore.QRect(20, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblEma34.setFont(font)
        self.lblEma34.setToolTipDuration(0)
        self.lblEma34.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblEma34.setIndent(0)
        self.lblEma34.setObjectName("lblEma34")
        self.headerFooter_2 = QtWidgets.QFrame(parent=self.loginFrame)
        self.headerFooter_2.setGeometry(QtCore.QRect(0, 370, 561, 20))
        self.headerFooter_2.setStyleSheet("background-color:#BCBCBC;\n"
"border:none\n"
"")
        self.headerFooter_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFooter_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFooter_2.setObjectName("headerFooter_2")
        self.txtSma20 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtSma20.setGeometry(QtCore.QRect(90, 140, 131, 21))
        self.txtSma20.setToolTipDuration(0)
        self.txtSma20.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtSma20.setReadOnly(True)
        self.txtSma20.setObjectName("txtSma20")
        self.lblSma20 = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblSma20.setGeometry(QtCore.QRect(20, 140, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblSma20.setFont(font)
        self.lblSma20.setToolTipDuration(0)
        self.lblSma20.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblSma20.setIndent(0)
        self.lblSma20.setObjectName("lblSma20")
        self.txtSma50 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtSma50.setGeometry(QtCore.QRect(90, 170, 131, 21))
        self.txtSma50.setToolTipDuration(0)
        self.txtSma50.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtSma50.setReadOnly(True)
        self.txtSma50.setObjectName("txtSma50")
        self.txtSma100 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtSma100.setGeometry(QtCore.QRect(90, 200, 131, 21))
        self.txtSma100.setToolTipDuration(0)
        self.txtSma100.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtSma100.setReadOnly(True)
        self.txtSma100.setObjectName("txtSma100")
        self.lblSma50 = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblSma50.setGeometry(QtCore.QRect(20, 170, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblSma50.setFont(font)
        self.lblSma50.setToolTipDuration(0)
        self.lblSma50.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblSma50.setIndent(0)
        self.lblSma50.setObjectName("lblSma50")
        self.lblSma100 = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblSma100.setGeometry(QtCore.QRect(20, 200, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblSma100.setFont(font)
        self.lblSma100.setToolTipDuration(0)
        self.lblSma100.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblSma100.setIndent(0)
        self.lblSma100.setObjectName("lblSma100")
        self.txtSma200 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtSma200.setGeometry(QtCore.QRect(90, 230, 131, 21))
        self.txtSma200.setToolTipDuration(0)
        self.txtSma200.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtSma200.setReadOnly(True)
        self.txtSma200.setObjectName("txtSma200")
        self.lblSma200 = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblSma200.setGeometry(QtCore.QRect(20, 230, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblSma200.setFont(font)
        self.lblSma200.setToolTipDuration(0)
        self.lblSma200.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblSma200.setIndent(0)
        self.lblSma200.setObjectName("lblSma200")
        self.txtAdx = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtAdx.setGeometry(QtCore.QRect(90, 270, 131, 21))
        self.txtAdx.setToolTipDuration(0)
        self.txtAdx.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtAdx.setReadOnly(True)
        self.txtAdx.setObjectName("txtAdx")
        self.txtRsi = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtRsi.setGeometry(QtCore.QRect(90, 300, 131, 21))
        self.txtRsi.setToolTipDuration(0)
        self.txtRsi.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtRsi.setReadOnly(True)
        self.txtRsi.setObjectName("txtRsi")
        self.lblAdx = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblAdx.setGeometry(QtCore.QRect(50, 270, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblAdx.setFont(font)
        self.lblAdx.setToolTipDuration(0)
        self.lblAdx.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblAdx.setIndent(0)
        self.lblAdx.setObjectName("lblAdx")
        self.lblRsi = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblRsi.setGeometry(QtCore.QRect(20, 300, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblRsi.setFont(font)
        self.lblRsi.setToolTipDuration(0)
        self.lblRsi.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblRsi.setIndent(0)
        self.lblRsi.setObjectName("lblRsi")
        self.lblRsiVolume = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblRsiVolume.setGeometry(QtCore.QRect(10, 330, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblRsiVolume.setFont(font)
        self.lblRsiVolume.setToolTipDuration(0)
        self.lblRsiVolume.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblRsiVolume.setIndent(0)
        self.lblRsiVolume.setObjectName("lblRsiVolume")
        self.txtRsiVolume = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtRsiVolume.setGeometry(QtCore.QRect(90, 330, 131, 21))
        self.txtRsiVolume.setToolTipDuration(0)
        self.txtRsiVolume.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtRsiVolume.setReadOnly(True)
        self.txtRsiVolume.setObjectName("txtRsiVolume")
        self.txtMarketCap = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtMarketCap.setGeometry(QtCore.QRect(420, 30, 131, 21))
        self.txtMarketCap.setToolTipDuration(0)
        self.txtMarketCap.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtMarketCap.setText("")
        self.txtMarketCap.setReadOnly(True)
        self.txtMarketCap.setObjectName("txtMarketCap")
        self.lblMarketCap = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblMarketCap.setGeometry(QtCore.QRect(330, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblMarketCap.setFont(font)
        self.lblMarketCap.setToolTipDuration(0)
        self.lblMarketCap.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblMarketCap.setObjectName("lblMarketCap")
        self.txtPriceToEarningsRatio = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtPriceToEarningsRatio.setGeometry(QtCore.QRect(420, 60, 131, 21))
        self.txtPriceToEarningsRatio.setToolTipDuration(0)
        self.txtPriceToEarningsRatio.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtPriceToEarningsRatio.setText("")
        self.txtPriceToEarningsRatio.setReadOnly(True)
        self.txtPriceToEarningsRatio.setObjectName("txtPriceToEarningsRatio")
        self.lblPriceToEarningsRatio = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblPriceToEarningsRatio.setGeometry(QtCore.QRect(270, 60, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblPriceToEarningsRatio.setFont(font)
        self.lblPriceToEarningsRatio.setToolTipDuration(0)
        self.lblPriceToEarningsRatio.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblPriceToEarningsRatio.setObjectName("lblPriceToEarningsRatio")
        self.txtEps = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtEps.setGeometry(QtCore.QRect(420, 90, 131, 21))
        self.txtEps.setToolTipDuration(0)
        self.txtEps.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtEps.setText("")
        self.txtEps.setReadOnly(True)
        self.txtEps.setObjectName("txtEps")
        self.lblEps = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblEps.setGeometry(QtCore.QRect(270, 90, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblEps.setFont(font)
        self.lblEps.setToolTipDuration(0)
        self.lblEps.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblEps.setObjectName("lblEps")
        self.lblDividendYield = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblDividendYield.setGeometry(QtCore.QRect(270, 120, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblDividendYield.setFont(font)
        self.lblDividendYield.setToolTipDuration(0)
        self.lblDividendYield.setStyleSheet("background-color: #CECECE;\n"
"color: black;")
        self.lblDividendYield.setObjectName("lblDividendYield")
        self.txtDividendYield = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtDividendYield.setGeometry(QtCore.QRect(420, 120, 131, 21))
        self.txtDividendYield.setToolTipDuration(0)
        self.txtDividendYield.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;\n"
"font-family: Futura;\n"
"font: 13px;")
        self.txtDividendYield.setText("")
        self.txtDividendYield.setReadOnly(True)
        self.txtDividendYield.setObjectName("txtDividendYield")
        Analysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Analysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 43))
        self.menubar.setObjectName("menubar")
        Analysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Analysis)
        self.statusbar.setObjectName("statusbar")
        Analysis.setStatusBar(self.statusbar)

        self.retranslateUi(Analysis)
        QtCore.QMetaObject.connectSlotsByName(Analysis)

    def retranslateUi(self, Analysis):
        _translate = QtCore.QCoreApplication.translate
        Analysis.setWindowTitle(_translate("Analysis", "Analysis"))
        self.btnProfileSettings.setText(_translate("Analysis", "Profile / Settings"))
        self.btnDashboard.setText(_translate("Analysis", "Dashboard"))
        self.btnHome.setText(_translate("Analysis", "Home"))
        self.lblDashboardHeader.setText(_translate("Analysis", " Analysis"))
        self.lblTitle.setText(_translate("Analysis", "BuddyTrade AI"))
        self.lblLogo.setText(_translate("Analysis", "logo"))
        self.btnSupport.setText(_translate("Analysis", "Support"))
        self.btnAbout.setText(_translate("Analysis", "About"))
        self.btnLinkedIn.setText(_translate("Analysis", "lkin"))
        self.btnGitHub.setText(_translate("Analysis", "git"))
        self.btnFAQs.setText(_translate("Analysis", "FAQs"))
        self.lblEma10.setText(_translate("Analysis", "  EMA 10:"))
        self.lblEma50.setText(_translate("Analysis", "  EMA 50:"))
        self.lblEma34.setText(_translate("Analysis", "  EMA 34:"))
        self.lblSma20.setText(_translate("Analysis", "  SMA 20:"))
        self.lblSma50.setText(_translate("Analysis", "  SMA 50:"))
        self.lblSma100.setText(_translate("Analysis", "SMA 100:"))
        self.lblSma200.setText(_translate("Analysis", "SMA 200:"))
        self.lblAdx.setText(_translate("Analysis", "ADX:"))
        self.lblRsi.setText(_translate("Analysis", "         RSI:"))
        self.lblRsiVolume.setText(_translate("Analysis", "RSI Volume:"))
        self.lblMarketCap.setText(_translate("Analysis", " Market Cap:"))
        self.lblPriceToEarningsRatio.setText(_translate("Analysis", " Price-to-Earnings Ratio:"))
        self.lblEps.setText(_translate("Analysis", "                    Basis EPS:"))
        self.lblDividendYield.setText(_translate("Analysis", "             Dividend Yield:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Analysis = QtWidgets.QMainWindow()
    ui = Ui_Analysis()
    ui.setupUi(Analysis)
    Analysis.show()
    sys.exit(app.exec())
