# Form implementation generated from reading ui file 'buy_page.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_PurchaseWindow(object):
    def setupUi(self, PurchaseWindow):
        PurchaseWindow.setObjectName("PurchaseWindow")
        PurchaseWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=PurchaseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.backgroundFrame.setGeometry(QtCore.QRect(0, 0, 801, 551))
        self.backgroundFrame.setStyleSheet("background-color: White")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.CenterPageBackgroundFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.CenterPageBackgroundFrame.setGeometry(QtCore.QRect(79, 49, 651, 421))
        self.CenterPageBackgroundFrame.setStyleSheet("background-color: #CECECE")
        self.CenterPageBackgroundFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.CenterPageBackgroundFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.CenterPageBackgroundFrame.setObjectName("CenterPageBackgroundFrame")
        self.lblTicker = QtWidgets.QLabel(parent=self.CenterPageBackgroundFrame)
        self.lblTicker.setGeometry(QtCore.QRect(200, 130, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(11)
        self.lblTicker.setFont(font)
        self.lblTicker.setObjectName("lblTicker")
        self.txtTicker = QtWidgets.QLineEdit(parent=self.CenterPageBackgroundFrame)
        self.txtTicker.setGeometry(QtCore.QRect(240, 130, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.txtTicker.setFont(font)
        self.txtTicker.setStyleSheet("background-color: White; color: black; font-family: Futura; font-size: 13")
        self.txtTicker.setText("")
        self.txtTicker.setObjectName("txtTicker")
        self.txtPurchasePrice = QtWidgets.QLineEdit(parent=self.CenterPageBackgroundFrame)
        self.txtPurchasePrice.setGeometry(QtCore.QRect(240, 160, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.txtPurchasePrice.setFont(font)
        self.txtPurchasePrice.setStyleSheet("background-color: White; color: black; font-family: Futura; font-size: 13")
        self.txtPurchasePrice.setText("")
        self.txtPurchasePrice.setObjectName("txtPurchasePrice")
        self.lblPurchasePrice = QtWidgets.QLabel(parent=self.CenterPageBackgroundFrame)
        self.lblPurchasePrice.setGeometry(QtCore.QRect(160, 160, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(11)
        self.lblPurchasePrice.setFont(font)
        self.lblPurchasePrice.setObjectName("lblPurchasePrice")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.CenterPageBackgroundFrame)
        self.txtQuantity.setGeometry(QtCore.QRect(240, 190, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.txtQuantity.setFont(font)
        self.txtQuantity.setStyleSheet("background-color: White; color: black; font-family: Futura; font-size: 13")
        self.txtQuantity.setText("")
        self.txtQuantity.setObjectName("txtQuantity")
        self.lblQuantity = QtWidgets.QLabel(parent=self.CenterPageBackgroundFrame)
        self.lblQuantity.setGeometry(QtCore.QRect(190, 190, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(11)
        self.lblQuantity.setFont(font)
        self.lblQuantity.setObjectName("lblQuantity")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.CenterPageBackgroundFrame)
        self.btnPurchase.setGeometry(QtCore.QRect(240, 230, 113, 32))
        self.btnPurchase.setStyleSheet("QPushButton {\n"
"   color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: Futura;\n"
"    font-size: 12px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}")
        self.btnPurchase.setObjectName("btnPurchase")
        PurchaseWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PurchaseWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        PurchaseWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PurchaseWindow)
        self.statusbar.setObjectName("statusbar")
        PurchaseWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PurchaseWindow)
        QtCore.QMetaObject.connectSlotsByName(PurchaseWindow)

    def retranslateUi(self, PurchaseWindow):
        _translate = QtCore.QCoreApplication.translate
        PurchaseWindow.setWindowTitle(_translate("PurchaseWindow", "Buy"))
        self.lblTicker.setText(_translate("PurchaseWindow", " Ticker:"))
        self.lblPurchasePrice.setText(_translate("PurchaseWindow", "Purchase Price:"))
        self.lblQuantity.setText(_translate("PurchaseWindow", "Quantity:"))
        self.btnPurchase.setText(_translate("PurchaseWindow", "Purchase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PurchaseWindow = QtWidgets.QMainWindow()
    ui = Ui_PurchaseWindow()
    ui.setupUi(PurchaseWindow)
    PurchaseWindow.show()
    sys.exit(app.exec())
