# Form implementation generated from reading ui file 'home_logged_out.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1021, 777)
        self.centralwidget = QtWidgets.QWidget(parent=Home)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.backgroundFrame.setGeometry(QtCore.QRect(-10, 0, 1031, 731))
        self.backgroundFrame.setStyleSheet("background-color:#F4F3F3;\n"
"border:none")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.headerFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 1031, 121))
        self.headerFrame.setStyleSheet("background-color: #CECECE;\n"
"")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.headerFooter = QtWidgets.QFrame(parent=self.headerFrame)
        self.headerFooter.setGeometry(QtCore.QRect(10, 104, 1021, 21))
        self.headerFooter.setStyleSheet("background-color:#BCBCBC;\n"
"border:none\n"
"")
        self.headerFooter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFooter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFooter.setObjectName("headerFooter")
        self.btnLogin = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnLogin.setGeometry(QtCore.QRect(900, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.btnDashboard = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnDashboard.setGeometry(QtCore.QRect(760, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnDashboard.setFont(font)
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnDashboard.setObjectName("btnDashboard")
        self.btnHome = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnHome.setGeometry(QtCore.QRect(620, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnHome.setFont(font)
        self.btnHome.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnHome.setObjectName("btnHome")
        self.lblDashboardHeader = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblDashboardHeader.setGeometry(QtCore.QRect(10, 70, 161, 31))
        self.lblDashboardHeader.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 20px;\n"
"   ")
        self.lblDashboardHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblDashboardHeader.setObjectName("lblDashboardHeader")
        self.lblTitle = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblTitle.setGeometry(QtCore.QRect(60, 10, 181, 31))
        self.lblTitle.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 20px;\n"
"   ")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.lblLogo = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblLogo.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.lblLogo.setObjectName("lblLogo")
        self.lineBetweenHomeAndDashboard = QtWidgets.QFrame(parent=self.headerFrame)
        self.lineBetweenHomeAndDashboard.setGeometry(QtCore.QRect(746, 13, 1, 45))
        self.lineBetweenHomeAndDashboard.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenHomeAndDashboard.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenHomeAndDashboard.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenHomeAndDashboard.setObjectName("lineBetweenHomeAndDashboard")
        self.lineBetweenDashboardAndProfileSettings = QtWidgets.QFrame(parent=self.headerFrame)
        self.lineBetweenDashboardAndProfileSettings.setGeometry(QtCore.QRect(885, 13, 1, 45))
        self.lineBetweenDashboardAndProfileSettings.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenDashboardAndProfileSettings.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenDashboardAndProfileSettings.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenDashboardAndProfileSettings.setObjectName("lineBetweenDashboardAndProfileSettings")
        self.footerFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.footerFrame.setGeometry(QtCore.QRect(10, 660, 1021, 61))
        self.footerFrame.setStyleSheet("background-color:#CECECE;\n"
"border:none")
        self.footerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footerFrame.setObjectName("footerFrame")
        self.btnSupport = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnSupport.setGeometry(QtCore.QRect(900, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnSupport.setFont(font)
        self.btnSupport.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnSupport.setObjectName("btnSupport")
        self.btnAbout = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnAbout.setGeometry(QtCore.QRect(760, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnAbout.setFont(font)
        self.btnAbout.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnAbout.setObjectName("btnAbout")
        self.btnLinkedIn = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnLinkedIn.setGeometry(QtCore.QRect(0, 30, 41, 21))
        self.btnLinkedIn.setObjectName("btnLinkedIn")
        self.btnGitHub = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnGitHub.setGeometry(QtCore.QRect(40, 30, 41, 21))
        self.btnGitHub.setObjectName("btnGitHub")
        self.lineBetweenAboutAndSupport = QtWidgets.QFrame(parent=self.footerFrame)
        self.lineBetweenAboutAndSupport.setGeometry(QtCore.QRect(885, 5, 1, 45))
        self.lineBetweenAboutAndSupport.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenAboutAndSupport.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenAboutAndSupport.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenAboutAndSupport.setObjectName("lineBetweenAboutAndSupport")
        self.lineBetweenFAQsAndAbout = QtWidgets.QFrame(parent=self.footerFrame)
        self.lineBetweenFAQsAndAbout.setGeometry(QtCore.QRect(746, 5, 1, 45))
        self.lineBetweenFAQsAndAbout.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenFAQsAndAbout.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenFAQsAndAbout.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenFAQsAndAbout.setObjectName("lineBetweenFAQsAndAbout")
        self.btnFAQs = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnFAQs.setGeometry(QtCore.QRect(620, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnFAQs.setFont(font)
        self.btnFAQs.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnFAQs.setObjectName("btnFAQs")
        self.btnRegister = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnRegister.setGeometry(QtCore.QRect(480, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnRegister.setFont(font)
        self.btnRegister.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnRegister.setObjectName("btnRegister")
        self.lineBetweenRegisterAndFAQs = QtWidgets.QFrame(parent=self.footerFrame)
        self.lineBetweenRegisterAndFAQs.setGeometry(QtCore.QRect(606, 5, 1, 45))
        self.lineBetweenRegisterAndFAQs.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenRegisterAndFAQs.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenRegisterAndFAQs.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenRegisterAndFAQs.setObjectName("lineBetweenRegisterAndFAQs")
        self.showcaseFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.showcaseFrame.setGeometry(QtCore.QRect(40, 150, 421, 351))
        self.showcaseFrame.setStyleSheet("background-color:#CECECE;\n"
"border:none")
        self.showcaseFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.showcaseFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.showcaseFrame.setObjectName("showcaseFrame")
        self.showcaseFrameFooter = QtWidgets.QFrame(parent=self.showcaseFrame)
        self.showcaseFrameFooter.setGeometry(QtCore.QRect(0, 250, 421, 21))
        self.showcaseFrameFooter.setStyleSheet("background-color:#BCBCBC;\n"
"border-bottom: 2px solid #3E3C3C;\ncolor: black;")
        self.showcaseFrameFooter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.showcaseFrameFooter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.showcaseFrameFooter.setObjectName("showcaseFrameFooter")
        self.showcaseFooterExtended = QtWidgets.QFrame(parent=self.showcaseFrame)
        self.showcaseFooterExtended.setGeometry(QtCore.QRect(0, 270, 421, 81))
        self.showcaseFooterExtended.setStyleSheet("background-color:#CECECE;\n"
"border:2px solid #BCBCBC;\ncolor: black;"
"")
        self.showcaseFooterExtended.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.showcaseFooterExtended.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.showcaseFooterExtended.setObjectName("showcaseFooterExtended")
        self.txtShowcase = QtWidgets.QTextEdit(parent=self.showcaseFooterExtended)
        self.txtShowcase.setGeometry(QtCore.QRect(0, 0, 421, 81))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(9)
        self.txtShowcase.setFont(font)
        self.txtShowcase.setObjectName("txtShowcase")
        self.stkSlideshow = QtWidgets.QStackedWidget(parent=self.showcaseFrame)
        self.stkSlideshow.setGeometry(QtCore.QRect(10, 10, 401, 231))
        self.stkSlideshow.setObjectName("stkSlideshow")
        self.pg1 = QtWidgets.QWidget()
        self.pg1.setObjectName("pg1")
        self.lblPg1 = QtWidgets.QLabel(parent=self.pg1)
        self.lblPg1.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg1.setObjectName("lblPg1")
        self.stkSlideshow.addWidget(self.pg1)
        self.pg2 = QtWidgets.QWidget()
        self.pg2.setObjectName("pg2")
        self.lblPg2 = QtWidgets.QLabel(parent=self.pg2)
        self.lblPg2.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg2.setObjectName("lblPg2")
        self.stkSlideshow.addWidget(self.pg2)
        self.pg3 = QtWidgets.QWidget()
        self.pg3.setObjectName("pg3")
        self.lblPg3 = QtWidgets.QLabel(parent=self.pg3)
        self.lblPg3.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg3.setObjectName("lblPg3")
        self.stkSlideshow.addWidget(self.pg3)
        self.pg4 = QtWidgets.QWidget()
        self.pg4.setObjectName("pg4")
        self.lblPg4 = QtWidgets.QLabel(parent=self.pg4)
        self.lblPg4.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg4.setObjectName("lblPg4")
        self.stkSlideshow.addWidget(self.pg4)
        self.pg5 = QtWidgets.QWidget()
        self.pg5.setObjectName("pg5")
        self.lblPg5 = QtWidgets.QLabel(parent=self.pg5)
        self.lblPg5.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg5.setObjectName("lblPg5")
        self.stkSlideshow.addWidget(self.pg5)
        self.pg6 = QtWidgets.QWidget()
        self.pg6.setObjectName("pg6")
        self.lblPg6 = QtWidgets.QLabel(parent=self.pg6)
        self.lblPg6.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg6.setObjectName("lblPg6")
        self.stkSlideshow.addWidget(self.pg6)
        self.pg7 = QtWidgets.QWidget()
        self.pg7.setObjectName("pg7")
        self.lblPg7 = QtWidgets.QLabel(parent=self.pg7)
        self.lblPg7.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg7.setObjectName("lblPg7")
        self.stkSlideshow.addWidget(self.pg7)
        self.pg8 = QtWidgets.QWidget()
        self.pg8.setObjectName("pg8")
        self.lblPg8 = QtWidgets.QLabel(parent=self.pg8)
        self.lblPg8.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg8.setObjectName("lblPg8")
        self.stkSlideshow.addWidget(self.pg8)
        self.pg9 = QtWidgets.QWidget()
        self.pg9.setObjectName("pg9")
        self.lblPg9 = QtWidgets.QLabel(parent=self.pg9)
        self.lblPg9.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg9.setObjectName("lblPg9")
        self.stkSlideshow.addWidget(self.pg9)
        self.pg10 = QtWidgets.QWidget()
        self.pg10.setObjectName("pg10")
        self.lblPg10 = QtWidgets.QLabel(parent=self.pg10)
        self.lblPg10.setGeometry(QtCore.QRect(10, 20, 381, 211))
        self.lblPg10.setObjectName("lblPg10")
        self.stkSlideshow.addWidget(self.pg10)
        self.tickerSearchFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.tickerSearchFrame.setGeometry(QtCore.QRect(40, 530, 421, 101))
        self.tickerSearchFrame.setStyleSheet("background-color:#CECECE; \n"
"border:none")
        self.tickerSearchFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tickerSearchFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tickerSearchFrame.setObjectName("tickerSearchFrame")
        self.ticketSearchFrameFooter = QtWidgets.QFrame(parent=self.tickerSearchFrame)
        self.ticketSearchFrameFooter.setGeometry(QtCore.QRect(0, 80, 421, 21))
        self.ticketSearchFrameFooter.setStyleSheet("background-color:#BCBCBC")
        self.ticketSearchFrameFooter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ticketSearchFrameFooter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ticketSearchFrameFooter.setObjectName("ticketSearchFrameFooter")
        self.txtTickerSearch = QtWidgets.QLineEdit(parent=self.tickerSearchFrame)
        self.txtTickerSearch.setGeometry(QtCore.QRect(110, 40, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.txtTickerSearch.setFont(font)
        self.txtTickerSearch.setStyleSheet("background-color:#BCBCBC;\n"
"border: 2px solid #3E3C3C;\ncolor: black;;")
        self.txtTickerSearch.setText("")
        self.txtTickerSearch.setObjectName("txtTickerSearch")
        self.lblTicker = QtWidgets.QLabel(parent=self.tickerSearchFrame)
        self.lblTicker.setGeometry(QtCore.QRect(40, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.lblTicker.setFont(font)
        self.lblTicker.setStyleSheet("background-color:#BCBCBC;\ncolor:black;")
        self.lblTicker.setObjectName("lblTicker")
        self.lblTickerHeader = QtWidgets.QLabel(parent=self.tickerSearchFrame)
        self.lblTickerHeader.setGeometry(QtCore.QRect(0, 5, 421, 16))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblTickerHeader.setFont(font)
        self.lblTickerHeader.setStyleSheet("border-bottom:2px solid #3E3C3C;\ncolor:black;")
        self.lblTickerHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTickerHeader.setObjectName("lblTickerHeader")
        self.btnAnalyzeTicker = QtWidgets.QPushButton(parent=self.tickerSearchFrame)
        self.btnAnalyzeTicker.setGeometry(QtCore.QRect(270, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnAnalyzeTicker.setFont(font)
        self.btnAnalyzeTicker.setStyleSheet("background-color:#BCBCBC;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\ncolor:black;")
        self.btnAnalyzeTicker.setObjectName("btnAnalyzeTicker")
        self.ticketSearchFrameFooter.raise_()
        self.lblTicker.raise_()
        self.txtTickerSearch.raise_()
        self.lblTickerHeader.raise_()
        self.btnAnalyzeTicker.raise_()
        self.marketUpdateFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.marketUpdateFrame.setGeometry(QtCore.QRect(480, 150, 521, 351))
        self.marketUpdateFrame.setStyleSheet("background-color:#CECECE;\n"
"border:none;\ncolor:black;")
        self.marketUpdateFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.marketUpdateFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.marketUpdateFrame.setObjectName("marketUpdateFrame")
        self.marketUpdateFrameFooter = QtWidgets.QFrame(parent=self.marketUpdateFrame)
        self.marketUpdateFrameFooter.setGeometry(QtCore.QRect(0, 330, 521, 21))
        self.marketUpdateFrameFooter.setStyleSheet("background-color:#BCBCBC")
        self.marketUpdateFrameFooter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.marketUpdateFrameFooter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.marketUpdateFrameFooter.setObjectName("marketUpdateFrameFooter")
        self.tblTickers = QtWidgets.QTableWidget(parent=self.marketUpdateFrame)
        self.tblTickers.setGeometry(QtCore.QRect(10, 30, 501, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(8)
        self.tblTickers.setFont(font)
        self.tblTickers.setStyleSheet("background-color:#BCBCBC;\n"
"border: 2px solid black;")
        self.tblTickers.setObjectName("tblTickers")
        self.tblTickers.setColumnCount(0)
        self.tblTickers.setRowCount(0)
        self.lblTickers = QtWidgets.QLabel(parent=self.marketUpdateFrame)
        self.lblTickers.setGeometry(QtCore.QRect(10, 10, 491, 16))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblTickers.setFont(font)
        self.lblTickers.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTickers.setObjectName("lblTickers")
        self.lblSummary = QtWidgets.QLabel(parent=self.marketUpdateFrame)
        self.lblSummary.setGeometry(QtCore.QRect(10, 60, 491, 16))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblSummary.setFont(font)
        self.lblSummary.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSummary.setObjectName("lblSummary")
        self.txtMarketSummary = QtWidgets.QTextEdit(parent=self.marketUpdateFrame)
        self.txtMarketSummary.setGeometry(QtCore.QRect(10, 90, 501, 231))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(9)
        self.txtMarketSummary.setFont(font)
        self.txtMarketSummary.setStyleSheet("background-color:#BCBCBC;\n"
"border:2px solid black;")
        self.txtMarketSummary.setObjectName("txtMarketSummary")
        self.marketMoversFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.marketMoversFrame.setGeometry(QtCore.QRect(480, 530, 521, 101))
        self.marketMoversFrame.setStyleSheet("background-color:#CECECE;\n"
"border:none")
        self.marketMoversFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.marketMoversFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.marketMoversFrame.setObjectName("marketMoversFrame")
        self.lblMarketMovers = QtWidgets.QLabel(parent=self.marketMoversFrame)
        self.lblMarketMovers.setGeometry(QtCore.QRect(-1, 10, 521, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblMarketMovers.setFont(font)
        self.lblMarketMovers.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblMarketMovers.setObjectName("lblMarketMovers")
        self.lblMarketMovers.setStyleSheet("color:black;")
        self.tblMarketMovers = QtWidgets.QTableWidget(parent=self.marketMoversFrame)
        self.tblMarketMovers.setGeometry(QtCore.QRect(10, 40, 501, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(8)
        self.tblMarketMovers.setFont(font)
        self.tblMarketMovers.setStyleSheet("background-color:#BCBCBC;\n"
"border: 2px solid black;")
        self.tblMarketMovers.setObjectName("tblMarketMovers")
        self.tblMarketMovers.setColumnCount(0)
        self.tblMarketMovers.setRowCount(0)
        self.cmbIntervals = QtWidgets.QComboBox(parent=self.marketMoversFrame)
        self.cmbIntervals.setGeometry(QtCore.QRect(430, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.cmbIntervals.setFont(font)
        self.cmbIntervals.setStyleSheet("background-color:#BCBCBC;\n"
"border: 2px solid black;\n\ncolor:black;"
"")
        self.cmbIntervals.setObjectName("cmbIntervals")
        self.cmbIntervals.addItem("Day")
        self.cmbIntervals.addItem("Week")
        self.cmbIntervals.addItem("Month")
        self.cmbIntervals.addItem("Year")
        self.lblInterval = QtWidgets.QLabel(parent=self.marketMoversFrame)
        self.lblInterval.setGeometry(QtCore.QRect(370, 10, 53, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblInterval.setFont(font)
        self.lblInterval.setObjectName("lblInterval")
        self.lblInterval.setStyleSheet("color:black;")
        self.marketMoversFrameFooter = QtWidgets.QFrame(parent=self.marketMoversFrame)
        self.marketMoversFrameFooter.setGeometry(QtCore.QRect(0, 80, 521, 21))
        self.marketMoversFrameFooter.setStyleSheet("background-color:#BCBCBC;\ncolor:black;")
        self.marketMoversFrameFooter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.marketMoversFrameFooter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.marketMoversFrameFooter.setObjectName("marketMoversFrameFooter")
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 43))
        self.menubar.setObjectName("menubar")
        Home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Home)
        self.statusbar.setObjectName("statusbar")
        Home.setStatusBar(self.statusbar)

        self.retranslateUi(Home)
        self.stkSlideshow.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Home"))
        self.btnLogin.setText(_translate("Home", "Login"))
        self.btnDashboard.setText(_translate("Home", "Dashboard"))
        self.btnHome.setText(_translate("Home", "Home"))
        self.lblDashboardHeader.setText(_translate("Home", " Home"))
        self.lblTitle.setText(_translate("Home", "BuddyTrade AI"))
        self.lblLogo.setText(_translate("Home", "logo"))
        self.btnSupport.setText(_translate("Home", "Support"))
        self.btnAbout.setText(_translate("Home", "About"))
        self.btnLinkedIn.setText(_translate("Home", "lkin"))
        self.btnGitHub.setText(_translate("Home", "git"))
        self.btnFAQs.setText(_translate("Home", "FAQs"))
        self.btnRegister.setText(_translate("Home", "Register"))
        self.txtShowcase.setHtml(_translate("Home", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Futura\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Futura\'; font-size:10pt; font-weight:600;\">BuddyTrade AI</span> is an intelligent portfolio analysis tool that delivers personalized buy, hold, or sell insights using real-time market data, technical indicators, and SEC filings. Powered by AI and Retrieval-Augmented Generation (RAG) via LlamaIndex, it explains investment recommendations in plain language. The app uses yFinance for live stock data and Pandas-TA for technical analysis, ensuring accurate and timely updates. Stay informed with daily summaries tailored to your portfolio.</p></body></html>"))
        self.lblPg1.setText(_translate("Home", "lblPg1"))
        self.lblPg2.setText(_translate("Home", "lblPg2"))
        self.lblPg3.setText(_translate("Home", "lblPg3"))
        self.lblPg4.setText(_translate("Home", "lblPg4"))
        self.lblPg5.setText(_translate("Home", "lblPg5"))
        self.lblPg6.setText(_translate("Home", "lblPg6"))
        self.lblPg7.setText(_translate("Home", "lblPg7"))
        self.lblPg8.setText(_translate("Home", "lblPg8"))
        self.lblPg9.setText(_translate("Home", "lblPg9"))
        self.lblPg10.setText(_translate("Home", "lblPg10"))
        self.lblTicker.setText(_translate("Home", "Stock Ticker:"))
        self.lblTickerHeader.setText(_translate("Home", "Enter a Stock Ticker to view Technical Data"))
        self.btnAnalyzeTicker.setText(_translate("Home", "Analyze"))
        self.lblTickers.setText(_translate("Home", "Trending Today in the Market"))
        self.lblSummary.setText(_translate("Home", "Market Summary"))
        self.lblMarketMovers.setText(_translate("Home", "Market Movers"))
        self.cmbIntervals.setItemText(0, _translate("Home", "Day"))
        self.cmbIntervals.setItemText(1, _translate("Home", "Week"))
        self.cmbIntervals.setItemText(2, _translate("Home", "Month"))
        self.cmbIntervals.setItemText(3, _translate("Home", "Year"))
        self.lblInterval.setText(_translate("Home", " Interval:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec())
