# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1021, 777)
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.backgroundFrame.setGeometry(QtCore.QRect(-10, 0, 1031, 731))
        self.backgroundFrame.setStyleSheet("background-color:#F4F3F3;\n"
"border:none")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.headerFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 1031, 121))
        self.headerFrame.setStyleSheet("background-color: #CECECE;\n"
"")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.headerFooter = QtWidgets.QFrame(parent=self.headerFrame)
        self.headerFooter.setGeometry(QtCore.QRect(10, 104, 1021, 21))
        self.headerFooter.setStyleSheet("background-color:#BCBCBC;\n"
"border:none\n"
"")
        self.headerFooter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFooter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFooter.setObjectName("headerFooter")
        self.btnLogin = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnLogin.setGeometry(QtCore.QRect(900, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.btnLogin.setFont(font)
        self.btnLogin.setAutoFillBackground(False)
        self.btnLogin.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.btnDashboard = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnDashboard.setGeometry(QtCore.QRect(760, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.btnDashboard.setFont(font)
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnDashboard.setObjectName("btnDashboard")
        self.btnHome = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnHome.setGeometry(QtCore.QRect(620, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.btnHome.setFont(font)
        self.btnHome.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnHome.setObjectName("btnHome")
        self.lblDashboardHeader = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblDashboardHeader.setGeometry(QtCore.QRect(10, 70, 161, 31))
        self.lblDashboardHeader.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 20px;\n"
"   ")
        self.lblDashboardHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblDashboardHeader.setObjectName("lblDashboardHeader")
        self.lblTitle = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblTitle.setGeometry(QtCore.QRect(60, 10, 181, 31))
        self.lblTitle.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 20px;\n"
"   ")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.lblLogo = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblLogo.setGeometry(QtCore.QRect(24, 11, 32, 32))
        self.lblLogo.setObjectName("lblLogo")
        pixmap = QPixmap("../resources/logo-removebg-preview.png")
        self.lblLogo.setPixmap(pixmap.scaled(32, 32, QtCore.Qt.AspectRatioMode.KeepAspectRatio, QtCore.Qt.TransformationMode.SmoothTransformation))
        self.lblLogo.setGeometry(QtCore.QRect(24, 11, 32, 32))
        self.lineBetweenHomeAndDashboard = QtWidgets.QFrame(parent=self.headerFrame)
        self.lineBetweenHomeAndDashboard.setGeometry(QtCore.QRect(746, 13, 1, 45))
        self.lineBetweenHomeAndDashboard.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenHomeAndDashboard.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenHomeAndDashboard.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenHomeAndDashboard.setObjectName("lineBetweenHomeAndDashboard")
        self.lineBetweenDashboardAndProfileSettings = QtWidgets.QFrame(parent=self.headerFrame)
        self.lineBetweenDashboardAndProfileSettings.setGeometry(QtCore.QRect(885, 13, 1, 45))
        self.lineBetweenDashboardAndProfileSettings.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenDashboardAndProfileSettings.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenDashboardAndProfileSettings.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenDashboardAndProfileSettings.setObjectName("lineBetweenDashboardAndProfileSettings")
        self.footerFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.footerFrame.setGeometry(QtCore.QRect(10, 660, 1021, 61))
        self.footerFrame.setStyleSheet("background-color:#CECECE;\n"
"border:none")
        self.footerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footerFrame.setObjectName("footerFrame")
        self.btnSupport = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnSupport.setGeometry(QtCore.QRect(900, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.btnSupport.setFont(font)
        self.btnSupport.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnSupport.setObjectName("btnSupport")
        self.btnAbout = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnAbout.setGeometry(QtCore.QRect(760, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.btnAbout.setFont(font)
        self.btnAbout.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnAbout.setObjectName("btnAbout")
        self.btnLinkedIn = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnLinkedIn.setGeometry(QtCore.QRect(0, 30, 32, 32))  # Adjust size as needed
        self.btnLinkedIn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnLinkedIn.setStyleSheet("""
        QPushButton {
                background-color: transparent;
                border: none;
        }
        QPushButton:hover {
                background-color: #B0B0B0;
                border-radius: 4px;
        }
        """)
        linkedin_icon = QtGui.QIcon("../resources/linkedin-logo-removebg-preview.png")  # Adjust if filename differs
        self.btnLinkedIn.setIcon(linkedin_icon)
        self.btnLinkedIn.setIconSize(QtCore.QSize(28, 28))
        self.btnLinkedIn.setToolTip("View LinkedIn")
        self.btnGitHub = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnGitHub.setGeometry(QtCore.QRect(40, 30, 32, 32))  # Adjust as needed
        self.btnGitHub.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnGitHub.setStyleSheet("""
        QPushButton {
                background-color: transparent;
                border: none;
        }
        QPushButton:hover {
                background-color: #B0B0B0;
                border-radius: 4px;
        }
        """)
        github_icon = QtGui.QIcon("../resources/github-logo-removebg-preview.png")  # Correct path from src/
        self.btnGitHub.setIcon(github_icon)
        self.btnGitHub.setIconSize(QtCore.QSize(36, 36))  # Slightly smaller than geometry
        self.btnGitHub.setToolTip("View GitHub")
        self.lineBetweenAboutAndSupport = QtWidgets.QFrame(parent=self.footerFrame)
        self.lineBetweenAboutAndSupport.setGeometry(QtCore.QRect(885, 5, 1, 45))
        self.lineBetweenAboutAndSupport.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenAboutAndSupport.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenAboutAndSupport.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenAboutAndSupport.setObjectName("lineBetweenAboutAndSupport")
        self.lineBetweenFAQsAndAbout = QtWidgets.QFrame(parent=self.footerFrame)
        self.lineBetweenFAQsAndAbout.setGeometry(QtCore.QRect(746, 5, 1, 45))
        self.lineBetweenFAQsAndAbout.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenFAQsAndAbout.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenFAQsAndAbout.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenFAQsAndAbout.setObjectName("lineBetweenFAQsAndAbout")
        self.btnFAQs = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnFAQs.setGeometry(QtCore.QRect(620, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.btnFAQs.setFont(font)
        self.btnFAQs.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnFAQs.setObjectName("btnFAQs")
        self.loginFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.loginFrame.setGeometry(QtCore.QRect(290, 220, 501, 311))
        self.loginFrame.setStyleSheet("background-color: #CECECE;\n"
"")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.txtEmail = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtEmail.setGeometry(QtCore.QRect(150, 110, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.txtEmail.setFont(font)
        self.txtEmail.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;")
        self.txtEmail.setObjectName("txtEmail")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtPassword.setGeometry(QtCore.QRect(150, 150, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.txtPassword.setFont(font)
        self.txtPassword.setStyleSheet("background-color:#F4F3F3;\n"
"color: black;")
        self.txtPassword.setText("")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.lblEmail = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblEmail.setGeometry(QtCore.QRect(100, 110, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblEmail.setFont(font)
        self.lblEmail.setStyleSheet("color: black;")
        self.lblEmail.setObjectName("lblEmail")
        self.lblPassword = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblPassword.setGeometry(QtCore.QRect(80, 150, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblPassword.setFont(font)
        self.lblPassword.setStyleSheet("color: black;")
        self.lblPassword.setObjectName("lblPassword")
        self.btnRegister = QtWidgets.QPushButton(parent=self.loginFrame)
        self.btnRegister.setGeometry(QtCore.QRect(210, 230, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.btnRegister.setFont(font)
        self.btnRegister.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"\n"
"   ")
        self.btnRegister.setObjectName("btnRegister")
        self.btnLoginUser = QtWidgets.QPushButton(parent=self.loginFrame)
        self.btnLoginUser.setGeometry(QtCore.QRect(210, 190, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(12)
        self.btnLoginUser.setFont(font)
        self.btnLoginUser.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12pt;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnLoginUser.setObjectName("btnLoginUser")
        self.centerPageFooter = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.centerPageFooter.setGeometry(QtCore.QRect(290, 511, 501, 20))
        self.centerPageFooter.setStyleSheet("background-color:#BCBCBC;\n"
"border:none\n"
"")
        self.centerPageFooter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.centerPageFooter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.centerPageFooter.setObjectName("centerPageFooter")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 43))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Home"))
        self.btnLogin.setText(_translate("Login", "Login"))
        self.btnDashboard.setText(_translate("Login", "Dashboard"))
        self.btnHome.setText(_translate("Login", "Home"))
        self.lblDashboardHeader.setText(_translate("Login", " Login"))
        self.lblTitle.setText(_translate("Login", "BuddyTrade AI"))
        self.btnSupport.setText(_translate("Login", "Support"))
        self.btnAbout.setText(_translate("Login", "About"))
        self.btnFAQs.setText(_translate("Login", "FAQs"))
        self.lblEmail.setText(_translate("Login", " Email:"))
        self.lblPassword.setText(_translate("Login", "Password:"))
        self.btnRegister.setText(_translate("Login", "Register"))
        self.btnLoginUser.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
