# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1021, 777)
        self.centralwidget = QtWidgets.QWidget(parent=Home)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.backgroundFrame.setGeometry(QtCore.QRect(-10, 0, 1031, 731))
        self.backgroundFrame.setStyleSheet("background-color:#F4F3F3;\n"
"border:none")
        self.backgroundFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.backgroundFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.backgroundFrame.setObjectName("backgroundFrame")
        self.headerFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.headerFrame.setGeometry(QtCore.QRect(0, 0, 1031, 121))
        self.headerFrame.setStyleSheet("background-color: #CECECE;\n"
"")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFrame.setObjectName("headerFrame")
        self.headerFooter = QtWidgets.QFrame(parent=self.headerFrame)
        self.headerFooter.setGeometry(QtCore.QRect(10, 104, 1021, 21))
        self.headerFooter.setStyleSheet("background-color:#BCBCBC;\n"
"border:none\n"
"")
        self.headerFooter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFooter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFooter.setObjectName("headerFooter")
        self.btnLogin = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnLogin.setGeometry(QtCore.QRect(900, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnLogin.setObjectName("btnLogin")
        self.btnDashboard = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnDashboard.setGeometry(QtCore.QRect(760, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnDashboard.setFont(font)
        self.btnDashboard.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnDashboard.setObjectName("btnDashboard")
        self.btnHome = QtWidgets.QPushButton(parent=self.headerFrame)
        self.btnHome.setGeometry(QtCore.QRect(620, 20, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnHome.setFont(font)
        self.btnHome.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnHome.setObjectName("btnHome")
        self.lblDashboardHeader = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblDashboardHeader.setGeometry(QtCore.QRect(10, 70, 161, 31))
        self.lblDashboardHeader.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 20px;\n"
"   ")
        self.lblDashboardHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblDashboardHeader.setObjectName("lblDashboardHeader")
        self.lblTitle = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblTitle.setGeometry(QtCore.QRect(60, 10, 181, 31))
        self.lblTitle.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 20px;\n"
"   ")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.lblLogo = QtWidgets.QLabel(parent=self.headerFrame)
        self.lblLogo.setGeometry(QtCore.QRect(30, 20, 16, 16))
        self.lblLogo.setObjectName("lblLogo")
        self.lineBetweenHomeAndDashboard = QtWidgets.QFrame(parent=self.headerFrame)
        self.lineBetweenHomeAndDashboard.setGeometry(QtCore.QRect(746, 13, 1, 45))
        self.lineBetweenHomeAndDashboard.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenHomeAndDashboard.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenHomeAndDashboard.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenHomeAndDashboard.setObjectName("lineBetweenHomeAndDashboard")
        self.lineBetweenDashboardAndProfileSettings = QtWidgets.QFrame(parent=self.headerFrame)
        self.lineBetweenDashboardAndProfileSettings.setGeometry(QtCore.QRect(885, 13, 1, 45))
        self.lineBetweenDashboardAndProfileSettings.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenDashboardAndProfileSettings.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenDashboardAndProfileSettings.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenDashboardAndProfileSettings.setObjectName("lineBetweenDashboardAndProfileSettings")
        self.footerFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.footerFrame.setGeometry(QtCore.QRect(10, 660, 1021, 61))
        self.footerFrame.setStyleSheet("background-color:#CECECE;\n"
"border:none")
        self.footerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.footerFrame.setObjectName("footerFrame")
        self.btnSupport = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnSupport.setGeometry(QtCore.QRect(900, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnSupport.setFont(font)
        self.btnSupport.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnSupport.setObjectName("btnSupport")
        self.btnAbout = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnAbout.setGeometry(QtCore.QRect(760, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnAbout.setFont(font)
        self.btnAbout.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnAbout.setObjectName("btnAbout")
        self.btnLinkedIn = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnLinkedIn.setGeometry(QtCore.QRect(0, 30, 41, 21))
        self.btnLinkedIn.setObjectName("btnLinkedIn")
        self.btnGitHub = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnGitHub.setGeometry(QtCore.QRect(40, 30, 41, 21))
        self.btnGitHub.setObjectName("btnGitHub")
        self.lineBetweenAboutAndSupport = QtWidgets.QFrame(parent=self.footerFrame)
        self.lineBetweenAboutAndSupport.setGeometry(QtCore.QRect(885, 5, 1, 45))
        self.lineBetweenAboutAndSupport.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenAboutAndSupport.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenAboutAndSupport.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenAboutAndSupport.setObjectName("lineBetweenAboutAndSupport")
        self.lineBetweenFAQsAndAbout = QtWidgets.QFrame(parent=self.footerFrame)
        self.lineBetweenFAQsAndAbout.setGeometry(QtCore.QRect(746, 5, 1, 45))
        self.lineBetweenFAQsAndAbout.setStyleSheet("background-color: Black;\n"
"min-width: 1px;\n"
"max-width:1px;")
        self.lineBetweenFAQsAndAbout.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.lineBetweenFAQsAndAbout.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lineBetweenFAQsAndAbout.setObjectName("lineBetweenFAQsAndAbout")
        self.btnFAQs = QtWidgets.QPushButton(parent=self.footerFrame)
        self.btnFAQs.setGeometry(QtCore.QRect(620, 10, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnFAQs.setFont(font)
        self.btnFAQs.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnFAQs.setObjectName("btnFAQs")
        self.loginFrame = QtWidgets.QFrame(parent=self.backgroundFrame)
        self.loginFrame.setGeometry(QtCore.QRect(290, 220, 501, 391))
        self.loginFrame.setStyleSheet("background-color: #CECECE;\n"
"")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.txtEmail = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtEmail.setGeometry(QtCore.QRect(160, 30, 241, 21))
        self.txtEmail.setToolTipDuration(0)
        self.txtEmail.setStyleSheet("background-color:#F4F3F3; color: black; font-family: Futura; font-size: 12px")
        self.txtEmail.setObjectName("txtEmail")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtPassword.setGeometry(QtCore.QRect(160, 150, 241, 21))
        self.txtPassword.setToolTipDuration(0)
        self.txtPassword.setStyleSheet("background-color:#F4F3F3; color: black; font-family: Futura; font-size: 12px")
        self.txtPassword.setObjectName("txtPassword")
        self.lblEmail = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblEmail.setGeometry(QtCore.QRect(110, 30, 41, 20))
        self.lblEmail.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n")
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblEmail.setFont(font)
        self.lblEmail.setToolTipDuration(0)
        self.lblEmail.setObjectName("lblEmail")
        self.lblPassword = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblPassword.setGeometry(QtCore.QRect(80, 150, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblPassword.setFont(font)
        self.lblPassword.setToolTipDuration(0)
        self.lblPassword.setIndent(0)
        self.lblPassword.setObjectName("lblPassword")
        self.lblPassword.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n")
        self.btnRegister = QtWidgets.QPushButton(parent=self.loginFrame)
        self.btnRegister.setGeometry(QtCore.QRect(220, 320, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.btnRegister.setFont(font)
        self.btnRegister.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    background-color: #BCBCBC;\n"
"    font-family: \'Futura\';\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0;\n"
"}\n"
"")
        self.btnRegister.setObjectName("btnRegister")
        self.txtVerifyEmail = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtVerifyEmail.setGeometry(QtCore.QRect(160, 60, 241, 21))
        self.txtVerifyEmail.setToolTipDuration(0)
        self.txtVerifyEmail.setStyleSheet("background-color:#F4F3F3; color: black; font-family: Futura; font-size: 12px")
        self.txtVerifyEmail.setObjectName("txtVerifyEmail")
        self.lblVerifyEmail = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblVerifyEmail.setGeometry(QtCore.QRect(74, 60, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblVerifyEmail.setFont(font)
        self.lblVerifyEmail.setToolTipDuration(0)
        self.lblVerifyEmail.setIndent(0)
        self.lblVerifyEmail.setObjectName("lblVerifyEmail")
        self.lblVerifyEmail.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n")
        self.headerFooter_2 = QtWidgets.QFrame(parent=self.loginFrame)
        self.headerFooter_2.setGeometry(QtCore.QRect(0, 370, 501, 20))
        self.headerFooter_2.setStyleSheet("background-color:#BCBCBC;\n"
"border:none\n"
"")
        self.headerFooter_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFooter_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.headerFooter_2.setObjectName("headerFooter_2")
        self.txtVerifyPassword = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtVerifyPassword.setGeometry(QtCore.QRect(160, 180, 241, 21))
        self.txtVerifyPassword.setToolTipDuration(0)
        self.txtVerifyPassword.setStyleSheet("background-color:#F4F3F3; color: black; font-family: Futura; font-size: 12px")
        self.txtVerifyPassword.setObjectName("txtVerifyPassword")
        self.lblVerifyPassword = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblVerifyPassword.setGeometry(QtCore.QRect(50, 180, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblVerifyPassword.setFont(font)
        self.lblVerifyPassword.setToolTipDuration(0)
        self.lblVerifyPassword.setIndent(0)
        self.lblVerifyPassword.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n")
        self.lblVerifyPassword.setObjectName("lblVerifyPassword")
        self.txtFirstName = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtFirstName.setGeometry(QtCore.QRect(160, 240, 241, 21))
        self.txtFirstName.setToolTipDuration(0)
        self.txtFirstName.setStyleSheet("background-color:#F4F3F3; color: black; font-family: Futura; font-size: 12px")
        self.txtFirstName.setObjectName("txtFirstName")
        self.txtLastName = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.txtLastName.setGeometry(QtCore.QRect(160, 270, 241, 21))
        self.txtLastName.setToolTipDuration(0)
        self.txtLastName.setStyleSheet("background-color:#F4F3F3; color: black; font-family: Futura; font-size: 12px")
        self.txtLastName.setReadOnly(False)
        self.txtLastName.setObjectName("txtLastName")
        self.lblFirstName = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblFirstName.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n")
        self.lblFirstName.setGeometry(QtCore.QRect(50, 240, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblFirstName.setFont(font)
        self.lblFirstName.setToolTipDuration(0)
        self.lblFirstName.setIndent(0)
        self.lblFirstName.setObjectName("lblFirstName")
        self.lblLastName = QtWidgets.QLabel(parent=self.loginFrame)
        self.lblLastName.setStyleSheet("color: Black;\n"
"font-family: \'Futura\';\n"
"font-size: 12px;\n")
        self.lblLastName.setGeometry(QtCore.QRect(50, 270, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Futura")
        self.lblLastName.setFont(font)
        self.lblLastName.setToolTipDuration(0)
        self.lblLastName.setIndent(0)
        self.lblLastName.setObjectName("lblLastName")
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 43))
        self.menubar.setObjectName("menubar")
        Home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Home)
        self.statusbar.setObjectName("statusbar")
        Home.setStatusBar(self.statusbar)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Home"))
        self.btnLogin.setText(_translate("Home", "Login"))
        self.btnDashboard.setText(_translate("Home", "Dashboard"))
        self.btnHome.setText(_translate("Home", "Home"))
        self.lblDashboardHeader.setText(_translate("Home", " Register"))
        self.lblTitle.setText(_translate("Home", "BuddyTrade AI"))
        self.lblLogo.setText(_translate("Home", "logo"))
        self.btnSupport.setText(_translate("Home", "Support"))
        self.btnAbout.setText(_translate("Home", "About"))
        self.btnLinkedIn.setText(_translate("Home", "lkin"))
        self.btnGitHub.setText(_translate("Home", "git"))
        self.btnFAQs.setText(_translate("Home", "FAQs"))
        self.lblEmail.setText(_translate("Home", " Email:"))
        self.lblPassword.setText(_translate("Home", "  Password:"))
        self.btnRegister.setText(_translate("Home", "Register"))
        self.lblVerifyEmail.setText(_translate("Home", " Verify Email:"))
        self.lblVerifyPassword.setText(_translate("Home", "Verify Password:"))
        self.lblFirstName.setText(_translate("Home", "        First Name:"))
        self.lblLastName.setText(_translate("Home", "        Last Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Register()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec())
